//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModTool.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModTool.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks and Parts.
        /// </summary>
        public static string BlocksNParts {
            get {
                return ResourceManager.GetString("BlocksNParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mod template for adding custom blocks, parts or scriptable objects.
        /// </summary>
        public static string BlocksNPartsDesc {
            get {
                return ResourceManager.GetString("BlocksNPartsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Respository.
        /// </summary>
        public static string CloneRepo {
            get {
                return ResourceManager.GetString("CloneRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get code from an online repository like GitHub or Azure DevOps.
        /// </summary>
        public static string CloneRepoDesc {
            get {
                return ResourceManager.GetString("CloneRepoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit or Stash.
        /// </summary>
        public static string ComOrStash {
            get {
                return ResourceManager.GetString("ComOrStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Without Code.
        /// </summary>
        public static string ContinueNoCode {
            get {
                return ResourceManager.GetString("ContinueNoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        public static string CreateBranch {
            get {
                return ResourceManager.GetString("CreateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Repository.
        /// </summary>
        public static string CreateRepo {
            get {
                return ResourceManager.GetString("CreateRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative.
        /// </summary>
        public static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Game.
        /// </summary>
        public static string CustomGame {
            get {
                return ResourceManager.GetString("CustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mod template for creating entirely new or modifying existing game logic.
        /// </summary>
        public static string CustomGameDesc {
            get {
                return ResourceManager.GetString("CustomGameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/01/2024.
        /// </summary>
        public static string DatePlaceholder {
            get {
                return ResourceManager.GetString("DatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        public static string Fetch {
            get {
                return ResourceManager.GetString("Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Explorer.
        /// </summary>
        public static string FileExplorer {
            get {
                return ResourceManager.GetString("FileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Files.
        /// </summary>
        public static string FindInFiles {
            get {
                return ResourceManager.GetString("FindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string FindPlaceHolder {
            get {
                return ResourceManager.GetString("FindPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindReplace {
            get {
                return ResourceManager.GetString("FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Document.
        /// </summary>
        public static string FormatDoc {
            get {
                return ResourceManager.GetString("FormatDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Selection.
        /// </summary>
        public static string FormatSelec {
            get {
                return ResourceManager.GetString("FormatSelec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU Image Manipulation Program.
        /// </summary>
        public static string GIMP {
            get {
                return ResourceManager.GetString("GIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        public static string Git {
            get {
                return ResourceManager.GetString("Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize New Repository.
        /// </summary>
        public static string InitRepo {
            get {
                return ResourceManager.GetString("InitRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert GUID.
        /// </summary>
        public static string InsertGuid {
            get {
                return ResourceManager.GetString("InsertGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json.
        /// </summary>
        public static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json References.
        /// </summary>
        public static string JsonRefs {
            get {
                return ResourceManager.GetString("JsonRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krita.
        /// </summary>
        public static string Krita {
            get {
                return ResourceManager.GetString("Krita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua.
        /// </summary>
        public static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua References.
        /// </summary>
        public static string LuaRefs {
            get {
                return ResourceManager.GetString("LuaRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Branches.
        /// </summary>
        public static string ManBranch {
            get {
                return ResourceManager.GetString("ManBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string MatchWord {
            get {
                return ResourceManager.GetString("MatchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maya 3D.
        /// </summary>
        public static string Maya {
            get {
                return ResourceManager.GetString("Maya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Paint.
        /// </summary>
        public static string MsPaint {
            get {
                return ResourceManager.GetString("MsPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My New Mod.
        /// </summary>
        public static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Project.
        /// </summary>
        public static string NewProj {
            get {
                return ResourceManager.GetString("NewProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a code template with scaffolding to get started.
        /// </summary>
        public static string NewProjDesc {
            get {
                return ResourceManager.GetString("NewProjDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Repository.
        /// </summary>
        public static string NewRepo {
            get {
                return ResourceManager.GetString("NewRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches Found.
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string Older {
            get {
                return ResourceManager.GetString("Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Local Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate and edit code within any folder.
        /// </summary>
        public static string OpenFolderDesc {
            get {
                return ResourceManager.GetString("OpenFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Bash.
        /// </summary>
        public static string OpenInBash {
            get {
                return ResourceManager.GetString("OpenInBash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Command Prompt.
        /// </summary>
        public static string OpenInCmd {
            get {
                return ResourceManager.GetString("OpenInCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in File Explorer.
        /// </summary>
        public static string OpenInExplor {
            get {
                return ResourceManager.GetString("OpenInExplor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Project.
        /// </summary>
        public static string OpenProj {
            get {
                return ResourceManager.GetString("OpenProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a local Junk File or Project.
        /// </summary>
        public static string OpenProjDesc {
            get {
                return ResourceManager.GetString("OpenProjDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent.
        /// </summary>
        public static string OpenRecent {
            get {
                return ResourceManager.GetString("OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Backward.
        /// </summary>
        public static string PageBackward {
            get {
                return ResourceManager.GetString("PageBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Forward.
        /// </summary>
        public static string PageForward {
            get {
                return ResourceManager.GetString("PageForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint 3D.
        /// </summary>
        public static string Paint3D {
            get {
                return ResourceManager.GetString("Paint3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.NET.
        /// </summary>
        public static string Paintdotnet {
            get {
                return ResourceManager.GetString("Paintdotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project will be created in.
        /// </summary>
        public static string PathCreation {
            get {
                return ResourceManager.GetString("PathCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Junk\AppData\Axolot Games\User_123456789\Mods\.
        /// </summary>
        public static string PathPlaceholder {
            get {
                return ResourceManager.GetString("PathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic&apos;s Junk Tool.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2024.
        /// </summary>
        public static string ProgramYear {
            get {
                return ResourceManager.GetString("ProgramYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Configurations.
        /// </summary>
        public static string ProjectConfig {
            get {
                return ResourceManager.GetString("ProjectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a description for my new amazing mod!.
        /// </summary>
        public static string ProjectDescPlaceholder {
            get {
                return ResourceManager.GetString("ProjectDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string Pull {
            get {
                return ResourceManager.GetString("Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebase.
        /// </summary>
        public static string Rebase {
            get {
                return ResourceManager.GetString("Rebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceOne {
            get {
                return ResourceManager.GetString("ReplaceOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Options.
        /// </summary>
        public static string ReplacePlaceholder {
            get {
                return ResourceManager.GetString("ReplacePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Path.
        /// </summary>
        public static string rPath {
            get {
                return ResourceManager.GetString("rPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Without Debugging.
        /// </summary>
        public static string RunNoDebug {
            get {
                return ResourceManager.GetString("RunNoDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Recent.
        /// </summary>
        public static string SearchRecent {
            get {
                return ResourceManager.GetString("SearchRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Templates.
        /// </summary>
        public static string SearchTemp {
            get {
                return ResourceManager.GetString("SearchTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Projects.
        /// </summary>
        public static string StartupProj {
            get {
                return ResourceManager.GetString("StartupProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Page.
        /// </summary>
        public static string SteamPg {
            get {
                return ResourceManager.GetString("SteamPg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Preview.
        /// </summary>
        public static string SteamPreview {
            get {
                return ResourceManager.GetString("SteamPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync (Pull then Push).
        /// </summary>
        public static string SyncInfo {
            get {
                return ResourceManager.GetString("SyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain Assets.
        /// </summary>
        public static string TerrainAssets {
            get {
                return ResourceManager.GetString("TerrainAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mod template for creating new or moddifying existing game / terrain assets.
        /// </summary>
        public static string TerrainAssetsDesc {
            get {
                return ResourceManager.GetString("TerrainAssetsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00 AM.
        /// </summary>
        public static string TimePlaceholder {
            get {
                return ResourceManager.GetString("TimePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Regular Expressions.
        /// </summary>
        public static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uuid.
        /// </summary>
        public static string UUID {
            get {
                return ResourceManager.GetString("UUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Code.
        /// </summary>
        public static string VisualStudioCode {
            get {
                return ResourceManager.GetString("VisualStudioCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Target Window(s).
        /// </summary>
        public static string WindowSelector {
            get {
                return ResourceManager.GetString("WindowSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
